server:
  port: 8084
  servlet:
    context-path: /homebudget

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homebudget?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Helsinki2018
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false